# Generated by Django 3.1.2 on 2020-10-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionlalimage_offer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additionlalimage',
            new_name='AdditionalImage',
        ),
    ]
