# Generated by Django 3.1.2 on 2020-11-02 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='price',
            field=models.FloatField(default=0, verbose_name='Предложить цену'),
        ),
    ]
