# Generated by Django 3.1.2 on 2020-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201102_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='measure',
            field=models.CharField(blank=True, choices=[('h', 'Час'), ('d', 'День'), ('w', 'Неделя'), ('m', 'Месяц')], max_length=1, null=True, verbose_name='Еденица времени'),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_amount',
            field=models.SmallIntegerField(default=0, verbose_name='Сделаю за'),
        ),
    ]
