# Generated by Django 3.1.2 on 2020-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201102_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rewievs',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
