# Generated by Django 3.1.2 on 2020-11-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_offer_rewievs'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='shared',
            field=models.IntegerField(default=0, verbose_name='Поделились'),
        ),
    ]
