# Generated by Django 3.1.3 on 2020-11-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_offer_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='rewievs',
            new_name='reviews',
        ),
    ]
