# Generated by Django 3.1.3 on 2020-11-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201105_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Новое'), ('a', 'Принято'), ('d', 'Выполнено')], default='n', max_length=1, null=True, verbose_name='Статус'),
        ),
    ]
