# Generated by Django 3.1.3 on 2020-11-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201106_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shauseravatar',
            old_name='avatar',
            new_name='image',
        ),
    ]
