# Generated by Django 3.1.3 on 2020-11-25 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201125_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to='main.offer', verbose_name='Предложение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
