# Generated by Django 3.1.3 on 2020-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201127_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='accuracy',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='cost',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='speed',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Скорость'),
        ),
    ]
