# Generated by Django 3.1.3 on 2020-12-01 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201130_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='shauser',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
