# Generated by Django 3.1.4 on 2020-12-03 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201202_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='shauser',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
