# Generated by Django 3.1.6 on 2021-05-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_shauser_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('parent_id', models.IntegerField(db_index=True, null=True, verbose_name='Родитель')),
                ('category', models.CharField(choices=[('О', 'область'), ('Р', 'район'), ('М', 'місто'), ('Т', 'смт'), ('С', 'село'), ('Щ', 'селище')], max_length=1, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
        migrations.AlterField(
            model_name='shauser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.place', verbose_name='Населенный пункт'),
        ),
    ]
