# Generated by Django 3.1.6 on 2021-05-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210520_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.IntegerField(verbose_name='ID для поиска')),
                ('name', models.CharField(max_length=256, verbose_name='Назване')),
            ],
        ),
        migrations.AlterField(
            model_name='shauser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location', verbose_name='Населенный пункт'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
