# Generated by Django 3.1.6 on 2021-02-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='shauser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.location', verbose_name='Населенный пункт'),
        ),
    ]
