# Generated by Django 3.1.6 on 2021-05-31 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210525_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location', verbose_name='населенный пункт'),
        ),
        migrations.AlterField(
            model_name='shauser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location', verbose_name='Населенный пункт'),
        ),
    ]
