# Generated by Django 3.1.6 on 2021-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210218_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('parent_id', models.IntegerField(db_index=True, null=True, verbose_name='Родитель')),
                ('category', models.CharField(choices=[('О', 'область'), ('Р', 'район'), ('М', 'місто'), ('Т', 'смт'), ('С', 'село'), ('Щ', 'селище')], max_length=1, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Координата', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterField(
            model_name='location',
            name='city_hall',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
