# Generated by Django 3.1.6 on 2021-07-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210531_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shauser',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.offer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
