# Generated by Django 5.2.6 on 2025-10-04 20:29

import django.db.models.deletion
import main.utilities
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210818_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={'verbose_name': 'Additional photo', 'verbose_name_plural': 'Additional photos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created'], 'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat messages'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='shauseravatar',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('super_category__order', 'super_category__name', 'order', 'name'), 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Super category', 'verbose_name_plural': 'Super categories'},
        ),
        migrations.AlterModelOptions(
            name='userreview',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offer', verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.supercategory', verbose_name='Super category'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='main.offer', verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='measure',
            field=models.CharField(blank=True, choices=[('h', 'Hour'), ('d', 'Day'), ('w', 'Week'), ('m', 'Month')], max_length=1, null=True, verbose_name='Measure'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offer', verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_amount',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Time amount'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.offer', verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='location',
            name='search_id',
            field=models.CharField(max_length=256, verbose_name='Search ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='Reviews count'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='shared',
            field=models.IntegerField(default=0, verbose_name='Share count'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'New'), ('a', 'Accepted'), ('d', 'Done')], db_index=True, default='n', max_length=1, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_offers', to=settings.AUTH_USER_MODEL, verbose_name='Executant'),
        ),
        migrations.AlterField(
            model_name='shauser',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Average rating'),
        ),
        migrations.AlterField(
            model_name='shauser',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Favorites'),
        ),
        migrations.AlterField(
            model_name='shauser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shauser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activated at'),
        ),
        migrations.AlterField(
            model_name='shauser',
            name='send_message',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Send messages?'),
        ),
        migrations.AlterField(
            model_name='shauseravatar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shauseravatar',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shauseravatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='accuracy',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='content',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='cost',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to='main.offer', verbose_name='Offer'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reviewal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL, verbose_name='Reviewal'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='speed',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Speed'),
        ),
    ]
